"""Ajout champ profile_image

Revision ID: 39993c7f1a35
Revises: 1110e51cfa0f
Create Date: 2025-06-06 14:43:49.085460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39993c7f1a35'
down_revision = '1110e51cfa0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###
